name: diga_la_app
description: "Diga Lá - Comunicação Aumentativa e Alternativa para crianças autistas."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  flutter_tts: ^4.2.2
  flutter_riverpod: ^2.6.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
